import type { DashboardMetric, Task } from "./types"

export const metrics: DashboardMetric[] = [
  { label: "Private tasks", value: "12", detail: "only commitments on-chain" },
  { label: "Sealed bids", value: "34", detail: "hidden until acceptance" },
  { label: "Receipts", value: "9", detail: "action logs + artifact hashes" },
  { label: "Settled", value: "7", detail: "paid after verification" },
]

export const tasks: Task[] = [
  {
    id: "ns-001",
    title: "Summarize partner docs with selective disclosure",
    requester: "Aurora Lab",
    status: "open",
    privacy: "private",
    reward: 180,
    currency: "USDC",
    dueAt: "2026-03-28T18:00:00.000Z",
    commitmentHash: "0x9f17d2b4c7e65e1d8f3a0b6c9e2f1a8d4c5b6a7e8f90123456789abcdef1234",
    brief: "Produce a concise partner-ready memo from a confidential brief.",
    privateBrief: "The full brief stays encrypted. Reveal only the memo and citation list.",
    disclosureScope: ["memo", "citation list", "acceptance note"],
    resultSummary: "Waiting for sealed bids.",
    receiptHash: "0x0f4b7c99ee31b113f2d6d2b5ec1a7f0b7b4a4d1d3d43c8a21c3bc4b0f0ab4001",
    execution: {
      transport: "libp2p",
      mode: "worker-hosted-model",
      networkPolicy: "allowlist-only",
      preferredProvider: "anthropic",
      providerAllowlist: ["anthropic", "openai", "ollama", "mock"],
      requiredCapabilities: ["text", "json"],
      toolProfile: ["fetch", "receipt"],
    },
    bids: [
      {
        id: "bid-001",
        worker: "lattice-node-12",
        amount: 160,
        currency: "USDC",
        durationHours: 6,
        note: "Providers: anthropic · Transports: libp2p, relay",
        status: "sealed",
        submittedAt: "2026-03-26T14:12:00.000Z",
      },
      {
        id: "bid-002",
        worker: "nightshift-7",
        amount: 175,
        currency: "USDC",
        durationHours: 4,
        note: "Providers: openai · Transports: http-poller, libp2p",
        status: "sealed",
        submittedAt: "2026-03-26T15:05:00.000Z",
      },
    ],
  },
  {
    id: "ns-002",
    title: "Generate a verifiable receipt for a local execution job",
    requester: "OpenShell",
    status: "assigned",
    privacy: "selective",
    reward: 240,
    currency: "USDC",
    dueAt: "2026-03-27T16:30:00.000Z",
    commitmentHash: "0x1c32dbe7f4c9a8b7e6d5c4f3a2b1c0987654fedcba0123456789fedcba987654",
    brief: "Run a local task and return a delivery receipt.",
    privateBrief: "Only the worker, reward, and artifact hash are visible until acceptance.",
    disclosureScope: ["worker id", "artifact hash", "receipt hash"],
    resultSummary: "Worker attached; execution pending.",
    receiptHash: "0x6b0b3c6c1f7ef2ea1cb3c1db9a7c8c0dd39f3a9445e1fbde4d8c06fdc0d4a213",
    execution: {
      transport: "http-poller",
      mode: "worker-hosted-model",
      networkPolicy: "allowlist-only",
      preferredProvider: "mock",
      providerAllowlist: ["openai", "xai", "mock"],
      requiredCapabilities: ["text", "json"],
      toolProfile: ["local-sandbox", "receipt"],
    },
    bids: [
      {
        id: "bid-003",
        worker: "proof-runner-3",
        amount: 240,
        currency: "USDC",
        durationHours: 3,
        note: "Providers: mock/local-sandbox · Transports: http-poller",
        status: "selected",
        submittedAt: "2026-03-26T12:40:00.000Z",
      },
    ],
  },
  {
    id: "ns-003",
    title: "Dashboard polish pass for the private beta",
    requester: "NightShift Team",
    status: "submitted",
    privacy: "public",
    reward: 90,
    currency: "USDC",
    dueAt: "2026-03-26T22:00:00.000Z",
    commitmentHash: "0xa11d25e3f31d8811c0a0c1c5aaee11ee99cfe8c9f0bdeee2f0f77b9a25d0f100",
    brief: "Tighten spacing, headings, and call to action clarity.",
    privateBrief: "No sensitive data. Keep it clean and beta-ready.",
    disclosureScope: ["before/after summary", "screenshot diff"],
    resultSummary: "Delivered. Ready for acceptance.",
    receiptHash: "0x50a4b6dd1a9018c4b0f4eab0e935a8fd8c1b7f1d7d05b6b38ce98f8d274c6c00",
    execution: {
      transport: "http-poller",
      mode: "tool-only",
      networkPolicy: "allowlist-only",
      requiredCapabilities: [],
      toolProfile: ["ui-audit", "receipt"],
    },
    bids: [
      {
        id: "bid-004",
        worker: "ui-node-4",
        amount: 90,
        currency: "USDC",
        durationHours: 2,
        note: "Providers: mock/ui-audit-runner · Transports: http-poller",
        status: "selected",
        submittedAt: "2026-03-26T11:08:00.000Z",
      },
    ],
  },
]

export function getTaskById(id: string) {
  return tasks.find(task => task.id === id) ?? null
}
